googleAnalytics = "UA-192987769-1"

baseURL = "https://the-coding-lab.com/"
languageCode = "en-us"
title = "The Coding Lab"
theme = "jeffprod"

# use github pages for deployment (docs)
publishDir = "docs"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

# html is omitted by default, turn this behavior off:
[markup.goldmark.renderer]
unsafe= true
